force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BK-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BookingArchiveBatch.cls
public class BookingArchiveBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id FROM Booking__c ' +
            'WHERE Booking_Date__c < LAST_N_YEARS:2 ' +
            'AND (Booking_Status__c = \'Cancelled\' ' +
            'OR Booking_Status__c = \'Refunded\')'
        );
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        System.debug('Archiving ' + scope.size() + ' records.');
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('BookingArchiveBatch completed.');
    }
}